sudo: false
language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -e .
script:
- 
deploy:
  provider: pypi
  user: azpycli
  password:
    secure: KR8oVFKCYdbhws/IcXMLdZXP+XYSAnyMv38RG4KyzfXyUGwozpiS+IePBxt+CbIEZtyJe/ZDEA48f27jFEH4QwV9lbdmjapR2/+hmT2meBqKhZ1NrtvIc4tJM3CD+G674cKVypwnTB9Rqav2BPjiM0i2ErX2HShuSXO2MCd0vfoeFJa3/LwIJ8r1iDoSWNhT40LI572FQjRpBBU/bpr1MSAtO5Sz7XWBIGBQo8MxejJedtMGhy4dVJfTHRhxd4gx4YrXvbIYkXdd1vMEr8AYy/0P62r2s3RyydUWpEr4g/5qkK2wB+EKz7kuHhbHTsfyDfW6PbAGkp1CfzQ6BcGvhSO/SWShtR+6s5MQzrAi2dLUIv2UGTbopCg386eENoL8PDtD0QLdBhdaIqaYcJYfyZ9nANiwmtDwbvetWvZ2mHoOSU2W/w5IXxnh7n1j20ECcB55BtqSRe5C1flGzMuz1BPyYgXbX5rWPi3PTsXrhz22MLH6oMC1hKg0HBZaHB414wjziya17h5WK4h2M6jh8eZRLwpVF2fLgUyCN2XzQY9LkVRuOtfwNtC4nPRgSVdCKAbELBY0q74cs8nKp7RIHmB3X/7BbPRz2bvzFwwdNTmxzv5FGldikbdrJY2sfLO7BTUbbe7T4B1r1d0eBHFG9a0XXrRFHEKLLQCu6kufklY=
  distributions: sdist bdist_wheel
  on:
    tags: true
